apiVersion: v1
kind: Service

metadata:
  name: pv-service

spec:
  selector:
   app : pv-app
  ports:
   - protocol: TCP
     port: 3000
     targetPort : 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deployment

spec:
  selector:
    matchLabels:
      app : pv-app
  template:
    metadata:
      labels:
        app: pv-app
    spec:
      containers:
        - name: pv-app
          image: haariskhatri/datademo:2
          volumeMounts:
            - mountPath: "/app/data"
              name: pv-storage
            
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim
        
  
      
  