apiVersion: v1 
kind: PersistentVolume
metadata:
  name: new-pv
  
spec:
  capacity:
   storage: 2Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate
  
